#! /bin/sh

# Monitors
bspc monitor -d 1 2 3 4 5 6 7 8 9 0

# Padding
bspc config top_padding        0
bspc config bottom_padding     0
bspc config left_padding       0
bspc config right_padding      0

# Borders and gaps
bspc config border_width         2
bspc config window_gap           5

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# Border colors
bspc config normal_border_color "#1D2821"
bspc config focused_border_color "#458588"
bspc config urgent_border_color "#CC241D"

# It looks like these options get overridden by Compton...
bspc config normal_frame_opacity 0.75
bspc config focused_frame_opacity 0.75

# Multihead behavior
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true

# Focusing behavior
bspc config focus_follows_pointer false
bspc config history_aware_focus true
bspc config focus_by_distance true

# Misc
bspc config split_ratio 0.50
bspc config auto_alternate true
bspc config auto_cancel true
bspc config initial_polarity first_child

# Rules
bspc rule -a Conky sticky=on manage=off lower=on
bspc rule -a xfce4-session floating=on fullscreen=on
bspc rule -a xfce4-panel floating=on manage=off
bspc rule -a wrapper-1.0 floating=on border=off focus=on
bspc rule -a Thunderbird floating=on
bspc rule -a Yad floating=on

# Autostart
~/.config/polybar/launch.sh 
feh --bg-center --bg-fill ./Pictures/background.jpg
dunst &
